### ISSUE TITLE
Expose handle of the decorated method after decoration

### ISSUE THREAD

**Issue by fterrazzoni** [getbannerman/decors#10]
Currently, we have access to `decorated_method`, which gives you the handle of the original method (BEFORE decoration). Most of the time, that's what we need, but I have a use case where I need to get the handle of the method AFTER it has been decorated 

@vmeyet : It has to do with priloo and I think this is the only way if we want to handle all edge cases properly. I will make a PR for you.

**Comment by vmeyet** [comment]
Ok, I can understand the use case

**Comment by vmeyet** [comment]
released
